# 18.063 Pset 1
Note: This is my first time ever using full LaTeX and Julia so please forgive any formatting errors. 

### Problem 1
I did find Part 2.5 (The Chain Rule) a bit confusing, as although I understood the chain rule in the specific case it explained here, it seems to only work when the differential term is "factored out" nicely. I had no idea what to do when you had f'(A)[dA] in terms of an expression involving dA's, and after re-reading though the section several times I still don't really know if the method I applied in problem 3 to do the chain rule is correct. Having a concrete example of composition where dA's can not be factored out nicely would help with this a lot. Thanks! 

### Problem 2
$$ df = f'(A)[dA] = (\nabla f)^T[dA] = d\lambda - \lambda $$
$$ (\nabla f)^T = (vv^T)^T = v^{TT}v^T = vv^T$$
$$ f'(A) = vec(vv^T) \cdot vec(dA) $$

In [55]:
using LinearAlgebra
A = randn(4,4)
δA = randn(4,4) * 1E-8
A = .5 * (A + A')

λ = eigvals(A)[1]
dλ = eigvals(A + δA)[1]
v = normalize(eigvecs(A)[:, 1]) # Assuming v_1 corresponds to λ_1
df_fd = dλ - λ
df_vvT = dot(vec(v*v'), vec(δA))

print("df from Forward Difference: ")
println(df_fd)
print("df assuming del(A) = vvT: ") 
println(df_vvT)

df from Forward Difference: -6.268996877167865e-9
df assuming del(A) = vvT: -6.268996603806086e-9


### Problem 3
#### 1. 
$$ f(x) = g.(x) = \begin{pmatrix} g(x_1) \\ g(x_2) \\ \vdots \end{pmatrix} $$
$$ df = \begin{pmatrix} g(x_1 + dx) - g(x_1) \\ g(x_2 + dx) - g(x_2) \\ \vdots \end{pmatrix} dx = \begin{pmatrix} g'(x_1) \\ g'(x_2) \\ \vdots \end{pmatrix} dx = g'.(x)dx $$
$$ df = g'.(x)dx = Jdx = \begin{pmatrix} g'(x_1) & \cdots & 0 \\ \vdots & \ddots & \vdots \\ 0 & \cdots & g'(x_n) \end{pmatrix} \begin{pmatrix} dx_1 \\ \vdots \\ dx_n \end{pmatrix} $$
$$ J = \begin{pmatrix} g'(x_1) & \cdots & 0 \\ \vdots & \ddots & \vdots \\ 0 & \cdots & g'(x_n) \end{pmatrix} $$
#### 2. 
$$ f(A) = (A^TA)^{-1} \rightarrow B = A^TA \rightarrow dB = A^TdA + dA^TA $$
$$ f(B) = B^{-1} \rightarrow df = -B^{-1}dBB^{-1} $$
$$ f'[dA] = -(A^TA)^{-1}(A^TdA + dA^TA)(A^TA)^{-1} $$ 
#### 3. 
$$ f(x) = (I + xx^T)^{-1}x \rightarrow B = (I + xx^T)^{-1} \rightarrow C = I + xx^T $$
$$ f(x) = Bx \rightarrow B = (C)^{-1} $$
$$ dC = xdx^T + dxx^T \rightarrow dB = -C^{-1}dCC^{-1} = (I + xx^T)^{-1}(xdx^T + dxx^T)(I + xx^T)^{-1} $$
$$ df = dBx + Bdx $$
$$ f'[dA] = (I + xx^T)^{-1}(xdx^T + dxx^T)(I + xx^T)^{-1}x + (I + xx^T)^{-1}dx $$
#### 4. 
$$ f(A) = tr(A^3) \rightarrow B = A^3 \rightarrow f(A) = tr(B) $$
$$ df = dtr(B) = tr(dB) = tr(dAA^2 + AdAA + A^2dA) $$
$$ tr(dAA^2) = tr(AdAA) = tr(A^2dA) \rightarrow df = tr(3A^2dA) $$ 
$$ df = \langle \nabla f, dA \rangle = tr((\nabla f)^TdA) = tr(3A^2dA)$$ 
$$ \nabla f = (3A^2)^T $$

### Problem 4
#### 1. 
$$ A \otimes (B \otimes C) = A \otimes \begin{pmatrix} b_{11} C & \cdots & b_{1n} C \\ \vdots & \ddots & \vdots \\ b_{m1} C & \cdots & b_{mn} C \end{pmatrix} = \begin{pmatrix} a_{11} \begin{pmatrix} b_{11} C & \cdots & b_{1n} C \\ \vdots & \ddots & \vdots \\ b_{m1} C & \cdots & b_{mn} C \end{pmatrix} & \cdots & a_{1n} \begin{pmatrix} b_{11} C & \cdots & b_{1n} C \\ \vdots & \ddots & \vdots \\ b_{m1} C & \cdots & b_{mn} C \end{pmatrix} \\ \vdots & \ddots & \vdots \\ a_{m1} \begin{pmatrix} b_{11} C & \cdots & b_{1n} C \\ \vdots & \ddots & \vdots \\ b_{m1} C & \cdots & b_{mn} C \end{pmatrix} & \cdots & a_{mn} \begin{pmatrix} b_{11} C & \cdots & b_{1n} C \\ \vdots & \ddots & \vdots \\ b_{m1} C & \cdots & b_{mn} C \end{pmatrix} \end{pmatrix} = \begin{pmatrix} a_{11} b_{11} C & \cdots & a_{1n} b_{1n} C \\ \vdots & \ddots & \vdots \\ a_{m1} b_{m1} C & \cdots & a_{mn} b_{mn} C \end{pmatrix} $$
$$ (A \otimes B) \otimes C = \begin{pmatrix} a_{11} B & \cdots & a_{1n} B \\ \vdots & \ddots & \vdots \\ a_{m1} B & \cdots & a_{mn} B \end{pmatrix} \otimes C = \begin{pmatrix} a_{11} b_{11} C & \cdots & a_{1n} b_{1n} C \\ \vdots & \ddots & \vdots \\ a_{m1} b_{m1} C & \cdots & a_{mn} b_{mn} C \end{pmatrix} = A \otimes (B \otimes C) $$
$$ A \otimes (B \otimes C) = (A \otimes B) \otimes C $$
#### 2. 
$$ (A \otimes B)(C \otimes D) = B(C \otimes D)A^T = B(D(A^T)C^T) = BD(I)A^TC^T = (AC \otimes BD)I = AC \otimes BD $$
$$ (A \otimes B)(C \otimes D) = AC \otimes BD $$

### Problem 5
#### 1. 
$$ M(\lambda) = \begin{pmatrix} M_{11}(\lambda) & \cdots & M_{1n}(\lambda) \\ \vdots & \ddots & \vdots \\ M_{n1}(\lambda) & \cdots & M_{nn}(\lambda) \end{pmatrix}  $$
$$ dM(\lambda) = \begin{pmatrix} M_{11}(\lambda + d\lambda) - M_{11}(\lambda)& \cdots & M_{11}(\lambda + d\lambda) - M_{1n}(\lambda) \\ \vdots & \ddots & \vdots \\ M_{11}(\lambda + d\lambda) - M_{n1}(\lambda) & \cdots & M_{nn}(\lambda + d\lambda) - M_{nn}(\lambda) \end{pmatrix} = \begin{pmatrix} M'_{11}(\lambda) & \cdots & M'_{1n}(\lambda) \\ \vdots & \ddots & \vdots \\ M'_{n1}(\lambda) & \cdots & M'_{nn}(\lambda) \end{pmatrix} d\lambda $$
$$ \frac{dM}{d\lambda} = \begin{pmatrix} M'_{11}(\lambda) & \cdots & M'_{1n}(\lambda) \\ \vdots & \ddots & \vdots \\ M'_{n1}(\lambda) & \cdots & M'_{nn}(\lambda) \end{pmatrix} $$
#### 2. 
$$ f(\lambda) = det(M(\lambda)) \rightarrow df = d(det(M)) = tr(det(M)M^{-1}dM) = tr(det(M)M^{-1}M'd\lambda) = det(M)tr(M^{-1}M')d\lambda $$
$$ \frac{df}{d\lambda} = det(M)tr(M^{-1}M') \rightarrow f'(\lambda)^{-1}f(\lambda) = \frac{det(M)}{det(M)tr(M^{-1}M')} $$
$$ f'(\lambda)^{-1}f(\lambda) = \frac{1}{tr(M^{-1}M')} $$
#### 3.

$$ M(\lambda) = A - \lambda I + \alpha sin(\lambda) B $$
$$ \frac{dM}{d\lambda} = -I + \alpha(cos(\lambda))B $$

In [56]:
using LinearAlgebra
A = [-2 -1 -7; -1 6 5; -7 5 6]
B = [7 -1 8; -1 7 -1; 8 -1 3]
α = .01
steps = 0

M(λ) = A - λ*I(3) + α*λ*sin(λ)*B
λ = argmax(eigvals(A))

while abs(det(M(λ))) > 1E-10
    λ = λ - 1/tr(inv(M(λ)) * (-I(3) + α*cos(λ)*B))
    steps += 1
end

print("λ: ")
println(round(λ, digits=7))
print("Steps: ")
println(steps)
print("Error: ")
println(abs(det(M(λ))))

λ: 3.0140319
Steps: 9
Error: 3.472181059884374e-11


### Problem 6
#### 1. 
$$ f(A) = e^A \rightarrow df = e^{A + dA} - e^{A} = f'(A)[dA] $$


In [60]:
using LinearAlgebra
A = randn(3, 3)
δA = randn(3, 3) * 1E-8
N = [A δA; zeros(3, 3) A]

eN_T = exp(N)
eN_C = [exp(A) exp(A + δA) - exp(A); zeros(3, 3) exp(A)]

display(eN_T[1:3,4:6])
display(eN_C[1:3,4:6])
display(N_T - N_C)

3×3 Matrix{Float64}:
  2.53057e-8  4.30745e-9  3.81891e-8
 -1.72424e-9  2.50053e-8  5.40647e-8
  3.44491e-8  2.14464e-9  7.72267e-8

3×3 Matrix{Float64}:
  2.53057e-8  4.30745e-9  3.81891e-8
 -1.72424e-9  2.50053e-8  5.40647e-8
  3.44491e-8  2.14464e-9  7.72267e-8

6×6 Matrix{Float64}:
 -1.11022e-16   5.55112e-17   0.0          …  -2.3965e-16   -4.54025e-16
  0.0           0.0           2.22045e-16      1.43804e-16   2.0605e-16
  0.0          -2.77556e-17  -1.11022e-16      1.27015e-17  -1.24926e-17
  0.0           0.0           0.0              5.55112e-17   0.0
  0.0           0.0           0.0              0.0           2.22045e-16
  0.0           0.0           0.0          …  -2.77556e-17  -1.11022e-16

#### 2. 
$$ f(A) = I \rightarrow f \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} = I $$
$$ \begin{pmatrix} f(A) & f'(A)[dA] \\ 0 & f(A) \end{pmatrix} = \begin{pmatrix} I & 0dA \\ 0 & I \end{pmatrix} = I $$ 
$$ f(A) = A \rightarrow f \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} = \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix}$$
$$ \begin{pmatrix} f(A) & f'(A)[dA] \\ 0 & f(A) \end{pmatrix} = \begin{pmatrix} A & 1dA \\ 0 & A \end{pmatrix} = \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} $$ 
$$ f(A) = A^2 \rightarrow f \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} = \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} = \begin{pmatrix} A^2 & AdA + dAA \\ 0 & A^2 \end{pmatrix} $$
$$ \begin{pmatrix} f(A) & f'(A)[dA] \\ 0 & f(A) \end{pmatrix} = \begin{pmatrix} A^2 & d(A^2) \\ 0 & A^2 \end{pmatrix} = \begin{pmatrix} A^2 & AdA + dAA \\ 0 & A^2 \end{pmatrix} $$ 
$$ f(A) = A^3 \rightarrow f \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} = \begin{pmatrix} A^2 & AdA + dAA \\ 0 & A^2 \end{pmatrix} \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} = \begin{pmatrix} A^3 & A^2dA + AdAA + dAA^2 \\ 0 & A^3 \end{pmatrix} $$
$$ \begin{pmatrix} f(A) & f'(A)[dA] \\ 0 & f(A) \end{pmatrix} = \begin{pmatrix} A^3 & d(A^3) \\ 0 & A^3 \end{pmatrix} = \begin{pmatrix} A^3 & A^2dA + AdAA + dAA^2 \\ 0 & A^3 \end{pmatrix} $$
#### 3. 
$$ d(A^{n}) = (A^{n})'[dA] = \sum_{m=1}^{n} A^{m-1}dAA^{n-m} \rightarrow d(A^{n-1}) = \sum_{m=1}^{n-1} A^{m-1}dAA^{n-1-m} $$
$$ P(n): \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} ^ {n-1} = \begin{pmatrix} A^{n-1} & (A^{n-1})'[dA] \\ 0 & A^{n-1} \end{pmatrix} = \begin{pmatrix} A^{n-1} & \sum_{m=1}^{n-1} A^{m-1}dAA^{n-1-m} \\ 0 & A^{n-1} \end{pmatrix} $$
$$ k = (n-1) + 1 = n \rightarrow n - 1 = k - 1 \rightarrow P(n) = P(k-1) $$
$$ \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} ^ {k} = \begin{pmatrix} A^{k-1} & \sum_{m=1}^{k-1} A^{m-1}dAA^{k-1-m} \\ 0 & A^{k-1} \end{pmatrix} \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} = \begin{pmatrix} A^{k} & A^{k-1}dA + \sum_{m=1}^{k-1} A^{m-1}dAA^{k-1-m}A \\ 0 & A^{k} \end{pmatrix} $$
$$ \sum_{m=1}^{k} A^{m-1}dAA^{k-m} = \sum_{m=1}^{k-1} A^{m-1}dAA^{k-1-m}A + A^{k-1}dA $$
$$ \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} ^ {k} = \begin{pmatrix} A^{k} & \sum_{m=1}^{k} A^{m-1}dAA^{k-m} \\ 0 & A^{k} \end{pmatrix} = P(k) $$
As $P(k=0)$ is true and $P(k)$ is true assuming $P(k-1)$ is true, $P(n)$ holds for all $n \geq 0$
#### 4. 
$$ \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} \begin{pmatrix} A^{-1} & -A^{-1}dAA^{-1} \\ 0 & A^{-1} \end{pmatrix} = \begin{pmatrix} 1 & -AA^{-1}dAA^{-1} + dAA^{-1} \\ 0 & 1 \end{pmatrix} =  \begin{pmatrix} 1 & -dAA^{-1} + dAA^{-1} \\ 0 & 1 \end{pmatrix} = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$
$$ \begin{pmatrix} A & dA \\ 0 & A \end{pmatrix} \begin{pmatrix} A^{-1} & -A^{-1}dAA^{-1} \\ 0 & A^{-1} \end{pmatrix} = I $$